// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['apiKeyWeb']!,
    appId: '1:489182630814:web:93b4676fa964512240fc8f',
    messagingSenderId: '489182630814',
    projectId: 'aroundu-403',
    authDomain: 'aroundu-403.firebaseapp.com',
    storageBucket: 'aroundu-403.appspot.com',
    measurementId: 'G-22Q1C2E5G8',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['apiKeyAndroid']!,
    appId: '1:489182630814:android:b76322ff2585163f40fc8f',
    messagingSenderId: '489182630814',
    projectId: 'aroundu-403',
    storageBucket: 'aroundu-403.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['apiKeyIos']!,
    appId: '1:489182630814:ios:b847ab9b2a929e3340fc8f',
    messagingSenderId: '489182630814',
    projectId: 'aroundu-403',
    storageBucket: 'aroundu-403.appspot.com',
    iosClientId: '489182630814-2qdjd5tcrvi6p7osfrto1begug8571dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
